'use strict';

let { execSync } = require('child_process');
let { writeFileSync } = require('fs');
let sleep = require('util').promisify(setTimeout);

const okayProveVersion = (function () {
    const config = {
        stdio: ['pipe', 'pipe', 'ignore']
    };

    try {
        let listings = execSync(`npm ls --prod --depth=0`, config);

        if (listings) {
            let pattern = /(?<=├── okay-prove@)[0-9.]+/;
            let match = pattern.exec(listings);

            return match ? match[0] : null;
        }
    } catch (err) {
        // Ignore
    }

    return null;
})();

console.log("Building with backend: okay-prove@" + okayProveVersion);

// Auto-generate backend version information
writeFileSync('src/okayProveVersion.autogenerated.ts', 'export default \"' + okayProveVersion + "\";");

// Let the file-system catch up
sleep(100);
