#!/usr/bin/env node

import { Command, Option } from 'commander';
import { main } from './main';
import implementationVersion from './okayProveVersion.autogenerated';

let program = new Command();

program
    .name('okay-prove')
    .version('0.0.1')
    .description('A CLI tool for automatically generating logical proofs\n\nBackend Version:\n  okay-prove@' + implementationVersion)
    .argument('<filename>', 'file with premises and conclusion')
    .option('-t, --trace', 'output known facts if unable to prove')
    .addOption(new Option('-f, --format <value>', "display format of proof").choices(['cascade', 'inline', 'latex', 'collapse']).default('inline'))
    .action(main)
    .parse(process.argv);
